services:
  - type: web
    name: helth-report-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9

  - type: web
    name: helth-report-frontend
    env: static
    buildCommand: cd static/frontend && npm install && npm run build
    staticPublishPath: static/frontend/build
    envVars:
      - key: NODE_VERSION
        value: 18 